# Basic workflow file, runs pytest and flake8 using tox
#
name: workflow

on:
  # Should run on any branch and pull request
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox and other packages
        run: pip install tox
      - name: Execute tox
        run: |
          tox -e asciify
          tox -e flake8
